import os
import numpy as np
from torch.utils.data import Dataset
from torchvision import transforms
import torch
import json
from PIL import Image
from sympy import Line, Point

# Compute the intersection between the 2 diagonal lines of the court rectangle
def generate_center(kps):
    x0, y0 = kps[0]
    x1, y1 = kps[1]
    x2, y2 = kps[2]
    x3, y3 = kps[3]
    
    point0 = Point(x0, y0)
    point1 = Point(x1, y1)
    point2 = Point(x2, y2)
    point3 = Point(x3, y3)
    
    line1 = Line(point0, point3)
    line2 = Line(point1, point2)
    
    intersection = line1.intersection(line2)
    
    center_x, center_y = intersection[0].coordinates
    
    return float(center_x), float(center_y)

# Function made based on the Gaussian heatmap generated by Claude for ball detection
def generate_gaussian_heatmap(h, w, x_target, y_target, variance):
    x_target = (x_target * w) / 1280.0
    y_target = (y_target * h) / 720.0
    x = np.arange(0, w, 1, np.float32)
    y = np.arange(0, h, 1, np.float32)
    y, x = np.meshgrid(y, x, indexing='ij')  # shape: (H, W)
    heatmap = np.exp(-((x - x_target)**2 + (y - y_target)**2) / (2 * variance))
    return torch.from_numpy(heatmap).unsqueeze(0)
        
def split_dataset(dataset, train=True, split=0.7):
    sep = int(split * len(dataset))
    
    if train == True:
        return dataset[:sep]
    else:
        return dataset[sep:]

class CourtDataset(Dataset):
    def __init__(self, root_dir="/scratch/users/andyjalloh/court_detection_github_dataset/", type="train", split=0.7, 
                 img_size=(640, 360), variance=10):
        super().__init__()
        self.root_dir = root_dir
        self.w, self.h = img_size
        self.variance = variance
        
        self.transform = transforms.Compose([
            transforms.Resize((self.h, self.w)),
            transforms.ToTensor(),
            transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
        ])

        self.path_images = os.path.join(self.root_dir, 'images')
        
        if type == "train":
            print("type = train")
            with open(os.path.join(self.root_dir, 'data_train.json'), 'r') as file:
                self.dataset = split_dataset(json.load(file), train=True)
        elif type == "val":
            print("type = val")
            with open(os.path.join(self.root_dir, 'data_train.json'), 'r') as file:
                self.dataset = split_dataset(json.load(file), train=False)
        elif type == "test":
            print("type = test")
            with open(os.path.join(self.root_dir, 'data_val.json'), 'r') as file:
                self.dataset = json.load(file)
        
    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, index):
        img_file = self.dataset[index]['id'] + '.png'
        img = self.transform(Image.open(os.path.join(self.path_images, img_file)).convert("RGB"))
        
        kps = self.dataset[index]['kps']
        
        heatmaps_list = []
        for kp in kps:
            heatmap = generate_gaussian_heatmap(self.h, self.w, kp[0], kp[1], self.variance)
            heatmaps_list.append(heatmap)
            
        heatmap_center = []
        
        center_x, center_y = generate_center(kps)
        
        heatmap_center = generate_gaussian_heatmap(self.h, self.w, center_x, center_y, self.variance)
        
        heatmaps = torch.cat(heatmaps_list + [heatmap_center], dim=0)
        
        return img, heatmaps